// SalamSeleb 홈페이지 문구 (데스크탑·모바일 공용) — ko / id / en
const L={
ko:{m_menu:"메뉴",m_close:"닫기",m_lang:"언어",m_all:"앱에서 전체 Seleb 보기",m_swipe:"옆으로 넘겨 보세요",m_bar1:"Seleb 둘러보기",m_bar2:"Seleb 되기",m_mobile:"모바일",nav_selebs:"Seleb",nav_how:"이용 방법",nav_safe:"안심 결제",nav_join:"Seleb 되기",nav_faq:"자주 묻는 질문",openApp:"앱 시제품 열기",
 hero_eyebrow:"찌까랑에서 시작하는 축하 영상 플랫폼",hero_h:"좋아하는 Seleb이<br><em>당신의 날</em>을 축하합니다",
 hero_p:"생일·결혼·돌잔치·회사 행사에 MC, 가수, 코미디언, 크리에이터가 이름을 불러 주는 맞춤 축하 영상을 신청하세요. 영상을 받고 만족할 때 정산됩니다.",
 cta_browse:"Seleb 둘러보기",cta_join:"Seleb으로 활동하기",faces_txt:"MC·가수·코미디언·크리에이터 등 9개 분야",hero_note:"출시 준비 중 · 지금은 사내 비공개 시제품입니다",
 mock_cap:"생일 축하 영상 · 워터마크 미리보기",mock_req:"영상 신청",mock_occ:"생일",mock_to:"받는 사람",mock_toV:"Sari (엄마)",mock_price:"금액",mock_when:"도착",mock_days:"3일 안에",mock_stamp:"영상 도착!",mock_stampS:"만족하면 정산돼요",mock_lbl:"예시 화면 · 사진은 AI로 만든 가상 인물",
 occ_eb:"이런 날에",occ_h:"특별한 날, 이름을 불러 주는 한마디",
 oc_birthday:"생일",oc_birthdayS:"이름을 불러 주는 생일 축하",oc_wedding:"결혼",oc_weddingS:"하객 앞에서 틀어 줄 축하 인사",oc_baby:"돌잔치·출산",oc_babyS:"새 가족을 맞는 축복 메시지",oc_company:"회사 행사",oc_companyS:"송년회·시상식·팀 응원",oc_cheer:"응원",oc_cheerS:"시험·경기·새 출발을 앞둔 사람에게",oc_other:"기타",oc_otherS:"원하는 내용을 자유롭게 부탁하세요",
 sel_eb:"Seleb",sel_h:"누구에게 부탁할까요?",sel_p:"분야별로 골라 보세요. 영상 가격과 응답 기간은 Seleb이 직접 정합니다.",all:"전체",
 cat_mc:"MC·사회자",cat_singer:"가수",cat_comedian:"코미디언",cat_creator:"크리에이터",cat_actor:"배우",cat_athlete:"운동선수",cat_dancer:"댄서",cat_magician:"마술사",cat_chef:"셰프",
 perVideo:"영상 1건",within:"{n}일 안에",sample:"샘플",sel_fine:"여기 보이는 Seleb은 모두 샘플(가상 인물)이며, 사진은 AI로 만든 예시 이미지입니다. 소개 글은 Seleb 본인이 쓰는 방식이라 인도네시아어로 두었습니다.",
 how_eb:"이용 방법",how_h:"신청부터 정산까지 4단계",
 st1:"신청",st1p:"Seleb을 고르고 받는 사람, 어떤 날인지, 전할 말을 적어 신청합니다. 결제 금액은 플랫폼이 보관합니다.",
 st2:"수락",st2p:"Seleb이 요청을 확인하고 수락하면 영상 제작이 시작됩니다.",
 st3:"전달",st3p:"영상이 도착하면 워터마크가 들어간 미리보기로 먼저 확인합니다.",
 st4:"정산",st4p:"‘만족’을 누르면 Seleb에게 지급되고, 고화질 원본을 받을 수 있습니다. 별점과 후기도 남겨 주세요.",
 safe_eb:"안심 장치",safe_h:"팬도 Seleb도 안심할 수 있게",
 sf1:"결제 보관",sf1p:"영상을 받고 확인할 때까지 결제 금액을 플랫폼이 보관합니다. 확인이 끝나야 Seleb에게 지급됩니다.",
 sf2:"도용 막는 미리보기",sf2p:"정산 전에는 저화질 워터마크 영상만 볼 수 있고 내려받을 수 없습니다.",
 sf3:"진짜 후기",sf3p:"거래를 마친 팬만 별 1~5개로 평가할 수 있고, Seleb은 후기에 답글을 달 수 있습니다.",
 join_eb:"Seleb 되기 · A그룹",join_h:"휴대폰 하나로 팬을 만나세요",join_p:"프로필을 올리고 가격과 응답 기간을 정하면 팬들의 영상 요청이 들어옵니다. 찍어서 올리면 끝입니다.",
 jp1:"영상 가격과 응답 기간은 직접 정합니다",jp2:"등급이 오를수록 홈과 추천 순 위쪽에 보입니다",jp3:"인도네시아어·영어·한국어 등 가능한 언어를 표시할 수 있습니다",join_cta:"Seleb 등록해 보기 (시제품)",
 tier_h:"Seleb 등급",tier_p:"완료한 영상 수와 팬 평균 별점으로 자동으로 정해집니다.",t_top:"탑",t_gold:"골드",t_silver:"실버",t_rising:"신규",
 tr_top:"완료 15건 이상 · 평균 4.7 이상",tr_gold:"완료 5건 이상 · 평균 4.5 이상",tr_silver:"완료 2건 이상 · 평균 4.0 이상",tr_rising:"그 밖의 모든 Seleb",
 biz_eb:"기업 고객",biz_h:"회사 행사에도 Seleb 축하 영상을",biz_p:"직원 생일, 송년회, 창립 기념일, 시상식에 Seleb 영상을 준비해 보세요. 기업 단체 주문은 출시 뒤 준비할 예정입니다.",
 bz1:"직원 생일 축하",bz2:"송년회·신년회",bz3:"창립 기념일",bz4:"시상식·팀 응원",
 faq_h:"자주 묻는 질문",
 q1:"SalamSeleb은 언제 출시되나요?",a1:"지금은 출시를 준비하고 있습니다. 먼저 찌까랑 지역에서 비공개 시범 운영을 하고, 일정이 정해지면 이 페이지에서 알려 드립니다.",
 q2:"영상은 얼마나 걸리나요?",a2:"Seleb마다 응답 기간이 다르며, 프로필에 ‘며칠 안에’로 표시됩니다.",
 q3:"영상이 마음에 들지 않으면요?",a3:"정산 전까지는 결제 금액을 플랫폼이 보관합니다. 불만족·환불 기준은 출시 전에 이용약관으로 안내합니다.",
 q4:"Seleb이 되려면 무엇이 필요한가요?",a4:"활동명, 분야, 소개, 영상 가격을 등록하면 됩니다. 정식 출시 때는 본인 확인 절차가 추가됩니다.",
 q5:"어떤 언어로 영상을 받을 수 있나요?",a5:"Seleb 프로필에 가능한 언어가 표시됩니다. 인도네시아어, 영어, 한국어, 자바어 등이 있습니다.",
 ft_internal:"사내 비공개 시안",ft1:"SalamSeleb · 법인 설립 준비 중 · SH그룹 신규 사업. 공개 전에 상표 출원과 법인 설립을 마칩니다.",ft2:"이 페이지의 Seleb과 사진은 모두 샘플이며 AI로 만든 가상 인물입니다. 실제 결제나 개인정보 수집은 없습니다."},
id:{m_menu:"Menu",m_close:"Tutup",m_lang:"Bahasa",m_all:"Lihat semua Seleb di aplikasi",m_swipe:"Geser untuk melihat",m_bar1:"Lihat Seleb",m_bar2:"Jadi Seleb",m_mobile:"Seluler",nav_selebs:"Seleb",nav_how:"Cara kerja",nav_safe:"Pembayaran aman",nav_join:"Jadi Seleb",nav_faq:"FAQ",openApp:"Buka prototipe",
 hero_eyebrow:"Platform video ucapan, mulai dari Cikarang",hero_h:"Seleb favoritmu<br>merayakan <em>harimu</em>",
 hero_p:"Pesan video ucapan personal dari MC, penyanyi, komedian, dan kreator yang menyebut namamu, untuk ulang tahun, pernikahan, syukuran, atau acara kantor. Pembayaran diteruskan setelah kamu puas.",
 cta_browse:"Lihat Seleb",cta_join:"Jadi Seleb",faces_txt:"9 bidang: MC, penyanyi, komedian, kreator, dan lainnya",hero_note:"Segera hadir · saat ini prototipe internal",
 mock_cap:"Video ulang tahun · pratinjau bertanda air",mock_req:"Pesanan video",mock_occ:"Ulang tahun",mock_to:"Untuk",mock_toV:"Sari (Ibu)",mock_price:"Harga",mock_when:"Tiba",mock_days:"≤ 3 hari",mock_stamp:"Video tiba!",mock_stampS:"Bayar diteruskan saat puas",mock_lbl:"Contoh tampilan · foto tokoh fiktif buatan AI",
 occ_eb:"Untuk momen ini",occ_h:"Hari spesial, ucapan yang menyebut namanya",
 oc_birthday:"Ulang tahun",oc_birthdayS:"Ucapan ulang tahun dengan nama",oc_wedding:"Pernikahan",oc_weddingS:"Ucapan untuk diputar di depan tamu",oc_baby:"Syukuran bayi",oc_babyS:"Doa untuk anggota keluarga baru",oc_company:"Acara kantor",oc_companyS:"Akhir tahun, penghargaan, semangat tim",oc_cheer:"Semangat",oc_cheerS:"Untuk ujian, lomba, dan awal baru",oc_other:"Lainnya",oc_otherS:"Minta isi ucapan sesukamu",
 sel_eb:"Seleb",sel_h:"Mau minta ucapan dari siapa?",sel_p:"Pilih berdasarkan bidang. Harga video dan waktu respons ditentukan oleh Seleb sendiri.",all:"Semua",
 cat_mc:"MC",cat_singer:"Penyanyi",cat_comedian:"Komedian",cat_creator:"Kreator",cat_actor:"Aktor",cat_athlete:"Atlet",cat_dancer:"Penari",cat_magician:"Pesulap",cat_chef:"Chef",
 perVideo:"per video",within:"≤ {n} hari",sample:"Contoh",sel_fine:"Semua Seleb di sini adalah contoh (tokoh fiktif) dan fotonya dibuat dengan AI.",
 how_eb:"Cara kerja",how_h:"4 langkah dari pesan sampai bayar",
 st1:"Pesan",st1p:"Pilih Seleb, tulis untuk siapa, acaranya apa, dan pesan yang ingin disampaikan. Pembayaran disimpan oleh platform.",
 st2:"Diterima",st2p:"Seleb memeriksa dan menerima permintaan, lalu mulai membuat video.",
 st3:"Dikirim",st3p:"Saat video tiba, kamu melihat pratinjau bertanda air lebih dulu.",
 st4:"Selesai",st4p:"Tekan ‘Puas’ dan pembayaran diteruskan ke Seleb. Video asli kualitas tinggi bisa diunduh. Jangan lupa beri rating.",
 safe_eb:"Rasa aman",safe_h:"Aman untuk fans dan Seleb",
 sf1:"Pembayaran ditahan",sf1p:"Platform menyimpan pembayaran sampai kamu menerima dan memeriksa video. Setelah itu baru diteruskan ke Seleb.",
 sf2:"Pratinjau anti-curi",sf2p:"Sebelum selesai, hanya video resolusi rendah bertanda air yang bisa ditonton, tanpa unduhan.",
 sf3:"Ulasan asli",sf3p:"Hanya fans yang sudah menyelesaikan transaksi yang bisa memberi 1–5 bintang, dan Seleb bisa membalas.",
 join_eb:"Jadi Seleb · Grup A",join_h:"Temui fans cukup dengan ponsel",join_p:"Unggah profil, tentukan harga dan waktu respons, lalu terima permintaan video dari fans. Rekam, unggah, selesai.",
 jp1:"Harga video dan waktu respons kamu tentukan sendiri",jp2:"Makin tinggi level, makin atas posisimu di beranda dan urutan rekomendasi",jp3:"Tampilkan bahasa yang kamu kuasai: Indonesia, Inggris, Korea, dan lainnya",join_cta:"Coba daftar Seleb (prototipe)",
 tier_h:"Level Seleb",tier_p:"Ditentukan otomatis dari jumlah video selesai dan rata-rata bintang dari fans.",t_top:"Top",t_gold:"Gold",t_silver:"Silver",t_rising:"Baru",
 tr_top:"≥ 15 selesai · rata-rata ≥ 4,7",tr_gold:"≥ 5 selesai · rata-rata ≥ 4,5",tr_silver:"≥ 2 selesai · rata-rata ≥ 4,0",tr_rising:"Semua Seleb lainnya",
 biz_eb:"Untuk perusahaan",biz_h:"Video Seleb untuk acara kantor",biz_p:"Siapkan video Seleb untuk ulang tahun karyawan, acara akhir tahun, HUT perusahaan, atau malam penghargaan. Pesanan grup untuk perusahaan akan disiapkan setelah peluncuran.",
 bz1:"Ulang tahun karyawan",bz2:"Acara akhir & awal tahun",bz3:"HUT perusahaan",bz4:"Penghargaan & semangat tim",
 faq_h:"Pertanyaan umum",
 q1:"Kapan SalamSeleb diluncurkan?",a1:"Kami sedang bersiap. Uji coba tertutup akan dimulai di Cikarang, dan jadwalnya akan diumumkan di halaman ini.",
 q2:"Berapa lama video dibuat?",a2:"Setiap Seleb punya waktu respons sendiri, tertulis di profil sebagai ‘≤ … hari’.",
 q3:"Kalau videonya kurang memuaskan?",a3:"Sebelum selesai, pembayaran tetap disimpan platform. Ketentuan ketidakpuasan dan pengembalian dana akan dijelaskan di syarat layanan sebelum peluncuran.",
 q4:"Apa yang dibutuhkan untuk jadi Seleb?",a4:"Daftarkan nama panggung, bidang, perkenalan, dan harga video. Saat peluncuran resmi akan ada verifikasi identitas.",
 q5:"Video bisa dalam bahasa apa?",a5:"Bahasa yang dikuasai tertulis di profil Seleb: Indonesia, Inggris, Korea, Jawa, dan lainnya.",
 ft_internal:"Draf internal",ft1:"SalamSeleb · badan usaha sedang dipersiapkan · usaha baru SH Group. Pendaftaran merek dan pendirian badan usaha diselesaikan sebelum dipublikasikan.",ft2:"Semua Seleb dan foto di halaman ini adalah contoh tokoh fiktif buatan AI. Tidak ada pembayaran nyata atau pengumpulan data pribadi."},
en:{m_menu:"Menu",m_close:"Close",m_lang:"Language",m_all:"See every Seleb in the app",m_swipe:"Swipe to see more",m_bar1:"Browse Selebs",m_bar2:"Become a Seleb",m_mobile:"Mobile",nav_selebs:"Selebs",nav_how:"How it works",nav_safe:"Safe payment",nav_join:"Become a Seleb",nav_faq:"FAQ",openApp:"Open prototype",
 hero_eyebrow:"Personal video greetings, starting in Cikarang",hero_h:"Your favorite Seleb<br>celebrates <em>your day</em>",
 hero_p:"Book a personal video from MCs, singers, comedians and creators who say your name, for birthdays, weddings, baby celebrations or office events. The Seleb gets paid once you’re happy.",
 cta_browse:"Browse Selebs",cta_join:"Become a Seleb",faces_txt:"9 fields: MCs, singers, comedians, creators and more",hero_note:"Coming soon · currently an internal prototype",
 mock_cap:"Birthday video · watermarked preview",mock_req:"Video request",mock_occ:"Birthday",mock_to:"For",mock_toV:"Sari (Mom)",mock_price:"Price",mock_when:"Arrives",mock_days:"within 3 days",mock_stamp:"Your video is here!",mock_stampS:"Paid out when you’re happy",mock_lbl:"Example screen · AI-generated fictional person",
 occ_eb:"For moments like",occ_h:"Special days, a greeting that says their name",
 oc_birthday:"Birthday",oc_birthdayS:"A birthday wish that uses their name",oc_wedding:"Wedding",oc_weddingS:"A message to play in front of the guests",oc_baby:"New baby",oc_babyS:"A blessing for the new family member",oc_company:"Office event",oc_companyS:"Year-end parties, awards, team spirit",oc_cheer:"Cheer",oc_cheerS:"Before an exam, a match or a new start",oc_other:"Anything else",oc_otherS:"Ask for whatever you like",
 sel_eb:"Selebs",sel_h:"Who should send it?",sel_p:"Pick by field. Each Seleb sets their own video price and response time.",all:"All",
 cat_mc:"MC",cat_singer:"Singer",cat_comedian:"Comedian",cat_creator:"Creator",cat_actor:"Actor",cat_athlete:"Athlete",cat_dancer:"Dancer",cat_magician:"Magician",cat_chef:"Chef",
 perVideo:"per video",within:"within {n} days",sample:"Sample",sel_fine:"Every Seleb shown here is a sample (fictional person) and the photos are AI-generated. Bios stay in Indonesian because Selebs write their own.",
 how_eb:"How it works",how_h:"Four steps from request to payout",
 st1:"Request",st1p:"Choose a Seleb and tell them who it’s for, the occasion and what to say. The platform holds your payment.",
 st2:"Accepted",st2p:"The Seleb reviews the request, accepts it and starts recording.",
 st3:"Delivered",st3p:"When the video arrives you watch a watermarked preview first.",
 st4:"Settled",st4p:"Tap ‘Happy’ to release payment to the Seleb and download the full-quality original. Leave a rating too.",
 safe_eb:"Peace of mind",safe_h:"Safe for fans and Selebs alike",
 sf1:"Payment held",sf1p:"The platform keeps your payment until you have received and checked the video. Only then is the Seleb paid.",
 sf2:"Copy-proof preview",sf2p:"Before settlement you can only watch a low-resolution, watermarked video, with no download.",
 sf3:"Real reviews",sf3p:"Only fans who completed a request can rate 1–5 stars, and Selebs can reply.",
 join_eb:"Become a Seleb · Group A",join_h:"Meet your fans with just a phone",join_p:"Upload a profile, set your price and response time, and fan requests start coming in. Record, upload, done.",
 jp1:"You set your own video price and response time",jp2:"Higher levels rank higher on the home page and in recommendations",jp3:"Show the languages you speak: Indonesian, English, Korean and more",join_cta:"Try Seleb sign-up (prototype)",
 tier_h:"Seleb levels",tier_p:"Set automatically from completed videos and the fans’ average rating.",t_top:"Top",t_gold:"Gold",t_silver:"Silver",t_rising:"Rising",
 tr_top:"15+ completed · 4.7+ average",tr_gold:"5+ completed · 4.5+ average",tr_silver:"2+ completed · 4.0+ average",tr_rising:"Every other Seleb",
 biz_eb:"For companies",biz_h:"Seleb videos for office events",biz_p:"Prepare Seleb videos for staff birthdays, year-end parties, company anniversaries or award nights. Group orders for companies are planned after launch.",
 bz1:"Staff birthdays",bz2:"Year-end & New Year parties",bz3:"Company anniversary",bz4:"Awards & team spirit",
 faq_h:"Frequently asked questions",
 q1:"When does SalamSeleb launch?",a1:"We are preparing for launch. A closed pilot will start in Cikarang first, and we’ll announce dates on this page.",
 q2:"How long does a video take?",a2:"Each Seleb has their own response time, shown on their profile as ‘within … days’.",
 q3:"What if I’m not happy with the video?",a3:"Until you settle, the platform holds your payment. The rules for dissatisfaction and refunds will be published in the terms of service before launch.",
 q4:"What do I need to become a Seleb?",a4:"Register a stage name, field, short bio and video price. Identity verification will be added at the official launch.",
 q5:"Which languages can videos be in?",a5:"Each Seleb profile lists the languages they speak: Indonesian, English, Korean, Javanese and more.",
 ft_internal:"Internal draft",ft1:"SalamSeleb · company in preparation · a new SH Group venture. Trademark filing and incorporation will be completed before this page goes public.",ft2:"All Selebs and photos on this page are samples of AI-generated fictional people. No real payments and no personal data collection."}
};
